name: Continous Integration
on: 
  push:
    branches:
      - main

env:
  node-version: "10.15.1"
      
jobs:
  test-frontend:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Node ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
        - name: npm install
        working-directory: ./frontend
        run: |
          npm install
        - name: run tests
        working-directory: ./frontend
        run: |
          npm run test-headless
  
  test-backend:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Node ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}
        - name: npm install
        working-directory: ./backend
        run: |
          npm install
        - name: run tests
        working-directory: ./backend
        run: |
          npm test

  build:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - uses: actions/checkout@v2
      - name: Node ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: npm install
        working-directory: ./
        run: |
          cd ./backend && npm install
          cd ./frontend && npm install

      - name: build frontend & move to backend
        working-directory: ./frontend
        run: |
          npm run build
          mkdir ../backend/public
          mv ./dist ../backend/public

      - name: replace backend .gitignore 
        working-directory: ./
        run: |
          rm ./backend/.gitignore
          cp .gitignore ./backend
          
      - name: Commit changes
        working-directory: ./
        run: |
          git config --global user.name "MMichotte"
          git config --global user.email "martin.michotte@gmail.com"
          git add .
          git commit -m "passed tests & build"
    
      - uses: akhileshns/heroku-deploy@v3.3.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-garage-test"
          heroku_email: "martin.michotte@gmail.com"
          appdir: "backend"
          