name: Continous Integration
on: 
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Frontend
        working-directory: ./frontend
        run: |
          npm test