name: Continous Integration
on: 
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.1]
    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: FRONTEND - npm install
        working-directory: ./frontend
        run: |
          npm install

      - name: FRONTEND - run tests
        working-directory: ./frontend
        run: |
          npm run test-headless  
      
      - name: FRONTEND - build & mv
        working-directory: ./frontend
        run: |
          npm run build
          mv ./dist ../backend/public

      - name: BACKEND - npm install
        working-directory: ./backend
        run: |
          npm install

      - name: BACKEND - run tests
        working-directory: ./backend
        run: |
          npm test

      - name: BACKEND - build
        working-directory: ./backend
        run: |
          npm run build
      