name: Continous Integration
on: 
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.16.1]
    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: FRONTEND - npm install
        working-directory: ./frontend
        run: |
          npm install

      - name: FRONTEND - run tests
        working-directory: ./frontend
        run: |
          npm test
      
      - name: FRONTEND - build & mv
        working-directory: ./frontend
        run: |
          npm build
          ls -a