name: Linting
on: [push]

env:
  node-version: 14.15.1

jobs:
  lint-frontend:
    if: "!contains(github.event.head_commit.message, 'Automated publish')"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
      - name: Lint
        run: |
          set +e
          npm run lint -- --fix
          set -e
      - name: push linted code to main
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          BRANCH_NAME: '${GITHUB_REF##*/}'
          
  
  lint-backend:
    if: "!contains(github.event.head_commit.message, 'Automated publish')"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          npm install
      - name: Lint
        run: |
          set +e
          npm run lint
          set -e
      - name: push linted code to main
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          BRANCH_NAME: '${GITHUB_REF##*/}'